import "@/styles/globals.css";

import { Header, Nav } from "./_layout";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans">
        <div className="grid h-lvh grid-cols-1 grid-rows-[4rem_minmax(0,_1fr)]">
          <Header />
          <div className="col-span-1">
            <Nav />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
